servers:
- name: server1
  mac: 12:12:12:12:12:12
  address: server1.domain.example
  ssh_user: user_of_server1_with_access_to_suspend
  ssh_key_filename: user_private_key
- name: server2
  mac: 34:34:34:34:34:34
  address: server2.domain.example
  ssh_user: user_of_server2_with_access_to_suspend
  ssh_key_filename: user_private_key
