servers:
- name: algiz
  mac: ec:8e:b5:77:a3:e8
  address: algiz.asfosnet.com
  ssh_user: root
  ssh_key_filename: wol_key
- name: isaz
  mac: 78:ac:c0:bc:dd:6d
  address: isaz.asfosnet.com
  ssh_user: root
  ssh_key_filename: wol_key
